[package]
name = "pledger"
version = "0.1.1"
authors = ["William Woodruff <william@yossarian.net>"]
edition = "2018"
description = "A small personal expense ledger"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/woodruffw/pledger"

[dependencies]
chrono = "0.4.11"
clap = "2.33.0"
env_logger = "0.7"
lazy_static = "1.4.0"
log = "0.4"
phf = { version = "0.8.0", features = ["macros"] }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
